Update git_submodule_update.yml

diff --git a/.github/workflows/git_submodule_update.yml b/.github/workflows/git_submodule_update.yml
--- a/.github/workflows/git_submodule_update.yml
+++ b/.github/workflows/git_submodule_update.yml
@@ -20,15 +20,15 @@ jobs:
         run: |
           git config user.name "GitHub Actions"
           git config user.email "actions@github.com"
+          git config core.autocrlf false
 
       - name: Update submodules
         run: |
-          # Attempt to update submodules, continue even if some fail
-          git submodule update --remote --merge || echo "Submodule update failed, proceeding..."
           # Ensure submodules are initialized
           git submodule init
-          # Try fetching specific branch if needed
-          git submodule foreach 'git fetch origin || true'
+          # Attempt to update submodules, continue even if some fail
+          git submodule update --remote --merge || echo "Submodule update failed, proceeding..."
+          git add .
 
       - name: Download Moodle version file
         run: |
@@ -46,6 +46,7 @@ jobs:
       - name: Check for changes
         id: check_changes
         run: |
+          git status
           if git diff --quiet; then
             echo "No changes in submodules"
             echo "has_changes=false" >> $GITHUB_OUTPUT
